name: Build and Push Docker Image to Docker Hub
on:
  push:
    branches:
      - main
    tags:
      - v*

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GIT_REF: ${{ github.head_ref || github.ref_name }} # ref_name to get tags/branches
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: set docker tag
        run: |
          echo "DOCKER_TAG=lucirleisantos/odoo_ee_17:$GIT_REF" >> $GITHUB_ENV
          
      - name: replace docker tag if master
        if: github.ref_name == 'master'
        run: |
          echo "DOCKER_TAG=lucirleisantos/chathub360:latest" >> $GITHUB_ENV
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: lucirleisantos
          password: dckr_pat_kMlwA40AEs0q0SvU8o2EUqHCYbc

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.DOCKER_TAG }}
