name: Build and Push Docker Image to Docker Hub

on: push
jobs:
  push_to_registry:
    name: push docker image to hub
    runs-on: ubuntu-latest
    steps:
      - name: check repository
        uses: actions/checkout@v4

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: lucirleisantos
          password: dckr_pat_kMlwA40AEs0q0SvU8o2EUqHCYbc

      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: DockerFileFolder/lucirleisantos/odoo_ee_17
          push: true
          tags: odoo_ee_17
